import styles from '@/styles/Home.module.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  async function handleOnSubmit(e) {
    e.preventDefault();
    const formData = {}
    Array.from(e.currentTarget.elements).forEach(field => {
      if (!field.name) return;
      formData[field.name] = field.value;
    })
    fetch('/api/mail', {
      method: "post",
      body: JSON.stringify(formData),
    })
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.grid} id='container'>
          <form method='post' id='grid' onSubmit={handleOnSubmit}>
            <p>
              <label htmlFor='name'>Name</label>
              <input type='text' name='name'/>
            </p>
            <p>
              <label htmlFor='email'>Email</label>
              <input type='email' name='email'/>
            </p>
            <p>
              <label htmlFor='message'>Message</label>
              <textarea name='message' />
            </p>
            <p>
              <button>Submit</button>
            </p>
          </form>
        </div>
      </main>
    </>
  )
}
